/*
    conStruct is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    conStruct is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with conStruct.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.17.0

#include <stan/model/model_header.hpp>

namespace model_space_multiK_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_space_multiK");
    reader.add_event(69, 69, "end", "model_space_multiK");
    return reader;
}

template <typename T1__, typename T2__, typename T3__, typename T4__, typename T5__>
Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__, T3__, T4__, typename boost::math::tools::promote_args<T5__>::type>::type, Eigen::Dynamic,Eigen::Dynamic>
spCov(const int& N,
          const T1__& a0,
          const T2__& aD,
          const T3__& a2,
          const Eigen::Matrix<T4__, Eigen::Dynamic,Eigen::Dynamic>& D,
          const T5__& phi, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__, T2__, T3__, T4__, typename boost::math::tools::promote_args<T5__>::type>::type fun_scalar_t__;
    typedef fun_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        fun_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 3;
        validate_non_negative_index("cov", "N", N);
        validate_non_negative_index("cov", "N", N);
        Eigen::Matrix<fun_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  cov(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
        (void) cov;  // dummy to suppress unused var warning

        stan::math::initialize(cov, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(cov,DUMMY_VAR__);


        current_statement_begin__ = 4;
        for (int i = 1; i <= N; ++i) {

            current_statement_begin__ = 5;
            for (int j = i; j <= N; ++j) {

                current_statement_begin__ = 6;
                stan::math::assign(get_base1_lhs(cov,i,j,"cov",1), ((a0 * exp(-(pow((aD * get_base1(D,i,j,"D",1)),a2)))) + phi));
                current_statement_begin__ = 7;
                stan::math::assign(get_base1_lhs(cov,j,i,"cov",1), get_base1(cov,i,j,"cov",1));
            }
        }
        current_statement_begin__ = 10;
        return stan::math::promote_scalar<fun_return_scalar_t__>(cov);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct spCov_functor__ {
    template <typename T1__, typename T2__, typename T3__, typename T4__, typename T5__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T1__, T2__, T3__, T4__, typename boost::math::tools::promote_args<T5__>::type>::type, Eigen::Dynamic,Eigen::Dynamic>
    operator()(const int& N,
          const T1__& a0,
          const T2__& aD,
          const T3__& a2,
          const Eigen::Matrix<T4__, Eigen::Dynamic,Eigen::Dynamic>& D,
          const T5__& phi, std::ostream* pstream__) const {
        return spCov(N, a0, aD, a2, D, phi, pstream__);
    }
};

template <typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__>
Eigen::Matrix<typename boost::math::tools::promote_args<T2__, T3__, T4__, T5__, typename boost::math::tools::promote_args<T6__, T7__, T8__, T9__>::type>::type, Eigen::Dynamic,Eigen::Dynamic>
admixed_covariance(const int& N,
                       const int& K,
                       const Eigen::Matrix<T2__, Eigen::Dynamic,1>& alpha0,
                       const Eigen::Matrix<T3__, Eigen::Dynamic,1>& alphaD,
                       const Eigen::Matrix<T4__, Eigen::Dynamic,1>& alpha2,
                       const Eigen::Matrix<T5__, Eigen::Dynamic,Eigen::Dynamic>& geoDist,
                       const Eigen::Matrix<T6__, Eigen::Dynamic,Eigen::Dynamic>& w_mat,
                       const Eigen::Matrix<T7__, Eigen::Dynamic,1>& nugget,
                       const Eigen::Matrix<T8__, Eigen::Dynamic,1>& phi,
                       const T9__& gamma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T2__, T3__, T4__, T5__, typename boost::math::tools::promote_args<T6__, T7__, T8__, T9__>::type>::type fun_scalar_t__;
    typedef fun_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        fun_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 13;
        validate_non_negative_index("parCov", "N", N);
        validate_non_negative_index("parCov", "N", N);
        Eigen::Matrix<fun_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  parCov(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
        (void) parCov;  // dummy to suppress unused var warning

        stan::math::initialize(parCov, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(parCov,DUMMY_VAR__);
        current_statement_begin__ = 14;
        validate_non_negative_index("Nug_mat", "N", N);
        validate_non_negative_index("Nug_mat", "N", N);
        Eigen::Matrix<fun_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  Nug_mat(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
        (void) Nug_mat;  // dummy to suppress unused var warning

        stan::math::initialize(Nug_mat, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(Nug_mat,DUMMY_VAR__);


        current_statement_begin__ = 15;
        stan::math::assign(parCov, rep_matrix(0,N,N));
        current_statement_begin__ = 16;
        stan::math::assign(Nug_mat, diag_matrix(nugget));
        current_statement_begin__ = 17;
        for (int k = 1; k <= K; ++k) {

            current_statement_begin__ = 18;
            stan::math::assign(parCov, add(parCov,elt_multiply(tcrossprod(to_matrix(stan::model::rvalue(w_mat, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list())), "w_mat"))),spCov(N,get_base1(alpha0,k,"alpha0",1),get_base1(alphaD,k,"alphaD",1),get_base1(alpha2,k,"alpha2",1),geoDist,get_base1(phi,k,"phi",1), pstream__))));
        }
        current_statement_begin__ = 20;
        stan::math::assign(parCov, add(add(gamma,parCov),Nug_mat));
        current_statement_begin__ = 21;
        return stan::math::promote_scalar<fun_return_scalar_t__>(parCov);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct admixed_covariance_functor__ {
    template <typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T2__, T3__, T4__, T5__, typename boost::math::tools::promote_args<T6__, T7__, T8__, T9__>::type>::type, Eigen::Dynamic,Eigen::Dynamic>
    operator()(const int& N,
                       const int& K,
                       const Eigen::Matrix<T2__, Eigen::Dynamic,1>& alpha0,
                       const Eigen::Matrix<T3__, Eigen::Dynamic,1>& alphaD,
                       const Eigen::Matrix<T4__, Eigen::Dynamic,1>& alpha2,
                       const Eigen::Matrix<T5__, Eigen::Dynamic,Eigen::Dynamic>& geoDist,
                       const Eigen::Matrix<T6__, Eigen::Dynamic,Eigen::Dynamic>& w_mat,
                       const Eigen::Matrix<T7__, Eigen::Dynamic,1>& nugget,
                       const Eigen::Matrix<T8__, Eigen::Dynamic,1>& phi,
                       const T9__& gamma, std::ostream* pstream__) const {
        return admixed_covariance(N, K, alpha0, alphaD, alpha2, geoDist, w_mat, nugget, phi, gamma, pstream__);
    }
};

template <typename T2__>
Eigen::Matrix<typename boost::math::tools::promote_args<T2__>::type, Eigen::Dynamic,Eigen::Dynamic>
make_w_matrix(const int& N,
                  const int& K,
                  const std::vector<Eigen::Matrix<T2__, Eigen::Dynamic,1> >& w, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T2__>::type fun_scalar_t__;
    typedef fun_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        fun_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 24;
        validate_non_negative_index("w_mat", "N", N);
        validate_non_negative_index("w_mat", "K", K);
        Eigen::Matrix<fun_scalar_t__,Eigen::Dynamic,Eigen::Dynamic>  w_mat(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(K));
        (void) w_mat;  // dummy to suppress unused var warning

        stan::math::initialize(w_mat, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(w_mat,DUMMY_VAR__);


        current_statement_begin__ = 25;
        for (int i = 1; i <= N; ++i) {

            current_statement_begin__ = 26;
            stan::math::assign(get_base1_lhs(w_mat,i,"w_mat",1), to_row_vector(get_base1(w,i,"w",1)));
        }
        current_statement_begin__ = 28;
        return stan::math::promote_scalar<fun_return_scalar_t__>(w_mat);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct make_w_matrix_functor__ {
    template <typename T2__>
        Eigen::Matrix<typename boost::math::tools::promote_args<T2__>::type, Eigen::Dynamic,Eigen::Dynamic>
    operator()(const int& N,
                  const int& K,
                  const std::vector<Eigen::Matrix<T2__, Eigen::Dynamic,1> >& w, std::ostream* pstream__) const {
        return make_w_matrix(N, K, w, pstream__);
    }
};

#include <meta_header.hpp>
 class model_space_multiK : public prob_grad {
private:
    int K;
    int N;
    int L;
    matrix_d obsCov;
    matrix_d geoDist;
    double varMeanFreqs;
    matrix_d LobsCov;
    vector_d dirConPar;
public:
    model_space_multiK(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_space_multiK(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_space_multiK_namespace::model_space_multiK";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 32;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            current_statement_begin__ = 33;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 34;
            context__.validate_dims("data initialization", "L", "int", context__.to_vec());
            L = int(0);
            vals_i__ = context__.vals_i("L");
            pos__ = 0;
            L = vals_i__[pos__++];
            current_statement_begin__ = 35;
            validate_non_negative_index("obsCov", "N", N);
            validate_non_negative_index("obsCov", "N", N);
            context__.validate_dims("data initialization", "obsCov", "matrix_d", context__.to_vec(N,N));
            validate_non_negative_index("obsCov", "N", N);
            validate_non_negative_index("obsCov", "N", N);
            obsCov = matrix_d(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
            vals_r__ = context__.vals_r("obsCov");
            pos__ = 0;
            size_t obsCov_m_mat_lim__ = N;
            size_t obsCov_n_mat_lim__ = N;
            for (size_t n_mat__ = 0; n_mat__ < obsCov_n_mat_lim__; ++n_mat__) {
                for (size_t m_mat__ = 0; m_mat__ < obsCov_m_mat_lim__; ++m_mat__) {
                    obsCov(m_mat__,n_mat__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 36;
            validate_non_negative_index("geoDist", "N", N);
            validate_non_negative_index("geoDist", "N", N);
            context__.validate_dims("data initialization", "geoDist", "matrix_d", context__.to_vec(N,N));
            validate_non_negative_index("geoDist", "N", N);
            validate_non_negative_index("geoDist", "N", N);
            geoDist = matrix_d(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
            vals_r__ = context__.vals_r("geoDist");
            pos__ = 0;
            size_t geoDist_m_mat_lim__ = N;
            size_t geoDist_n_mat_lim__ = N;
            for (size_t n_mat__ = 0; n_mat__ < geoDist_n_mat_lim__; ++n_mat__) {
                for (size_t m_mat__ = 0; m_mat__ < geoDist_m_mat_lim__; ++m_mat__) {
                    geoDist(m_mat__,n_mat__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 37;
            context__.validate_dims("data initialization", "varMeanFreqs", "double", context__.to_vec());
            varMeanFreqs = double(0);
            vals_r__ = context__.vals_r("varMeanFreqs");
            pos__ = 0;
            varMeanFreqs = vals_r__[pos__++];

            // validate, data variables
            current_statement_begin__ = 32;
            check_greater_or_equal(function__,"K",K,1);
            current_statement_begin__ = 33;
            check_greater_or_equal(function__,"N",N,2);
            current_statement_begin__ = 34;
            check_greater_or_equal(function__,"L",L,(N + 1));
            current_statement_begin__ = 35;
            current_statement_begin__ = 36;
            current_statement_begin__ = 37;
            // initialize data variables
            current_statement_begin__ = 40;
            validate_non_negative_index("LobsCov", "N", N);
            validate_non_negative_index("LobsCov", "N", N);
            LobsCov = matrix_d(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
            stan::math::fill(LobsCov,DUMMY_VAR__);
            current_statement_begin__ = 41;
            validate_non_negative_index("dirConPar", "K", K);
            dirConPar = vector_d(static_cast<Eigen::VectorXd::Index>(K));
            stan::math::fill(dirConPar,DUMMY_VAR__);

            current_statement_begin__ = 42;
            stan::math::assign(LobsCov, multiply(L,obsCov));
            current_statement_begin__ = 43;
            stan::math::assign(dirConPar, rep_vector(0.10000000000000001,K));

            // validate transformed data
            current_statement_begin__ = 40;
            current_statement_begin__ = 41;

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 46;
            validate_non_negative_index("alpha0", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 47;
            validate_non_negative_index("alphaD", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 48;
            validate_non_negative_index("alpha2", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 49;
            validate_non_negative_index("phi", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 50;
            validate_non_negative_index("nugget", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 51;
            validate_non_negative_index("w", "K", K);
            validate_non_negative_index("w", "N", N);
            num_params_r__ += (K - 1) * N;
            current_statement_begin__ = 52;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_space_multiK() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("alpha0")))
            throw std::runtime_error("variable alpha0 missing");
        vals_r__ = context__.vals_r("alpha0");
        pos__ = 0U;
        validate_non_negative_index("alpha0", "K", K);
        context__.validate_dims("initialization", "alpha0", "vector_d", context__.to_vec(K));
        vector_d alpha0(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            alpha0(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,alpha0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha0: ") + e.what());
        }

        if (!(context__.contains_r("alphaD")))
            throw std::runtime_error("variable alphaD missing");
        vals_r__ = context__.vals_r("alphaD");
        pos__ = 0U;
        validate_non_negative_index("alphaD", "K", K);
        context__.validate_dims("initialization", "alphaD", "vector_d", context__.to_vec(K));
        vector_d alphaD(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            alphaD(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,alphaD);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alphaD: ") + e.what());
        }

        if (!(context__.contains_r("alpha2")))
            throw std::runtime_error("variable alpha2 missing");
        vals_r__ = context__.vals_r("alpha2");
        pos__ = 0U;
        validate_non_negative_index("alpha2", "K", K);
        context__.validate_dims("initialization", "alpha2", "vector_d", context__.to_vec(K));
        vector_d alpha2(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            alpha2(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lub_unconstrain(0,2,alpha2);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha2: ") + e.what());
        }

        if (!(context__.contains_r("phi")))
            throw std::runtime_error("variable phi missing");
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        validate_non_negative_index("phi", "K", K);
        context__.validate_dims("initialization", "phi", "vector_d", context__.to_vec(K));
        vector_d phi(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            phi(j1__) = vals_r__[pos__++];
        try {
            writer__.positive_ordered_unconstrain(phi);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable phi: ") + e.what());
        }

        if (!(context__.contains_r("nugget")))
            throw std::runtime_error("variable nugget missing");
        vals_r__ = context__.vals_r("nugget");
        pos__ = 0U;
        validate_non_negative_index("nugget", "N", N);
        context__.validate_dims("initialization", "nugget", "vector_d", context__.to_vec(N));
        vector_d nugget(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            nugget(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,nugget);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable nugget: ") + e.what());
        }

        if (!(context__.contains_r("w")))
            throw std::runtime_error("variable w missing");
        vals_r__ = context__.vals_r("w");
        pos__ = 0U;
        validate_non_negative_index("w", "N", N);
        validate_non_negative_index("w", "K", K);
        context__.validate_dims("initialization", "w", "vector_d", context__.to_vec(N,K));
        std::vector<vector_d> w(N,vector_d(static_cast<Eigen::VectorXd::Index>(K)));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            for (int i0__ = 0U; i0__ < N; ++i0__)
                w[i0__](j1__) = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < N; ++i0__)
            try {
            writer__.simplex_unconstrain(w[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w: ") + e.what());
        }

        if (!(context__.contains_r("gamma")))
            throw std::runtime_error("variable gamma missing");
        vals_r__ = context__.vals_r("gamma");
        pos__ = 0U;
        context__.validate_dims("initialization", "gamma", "double", context__.to_vec());
        double gamma(0);
        gamma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,gamma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable gamma: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<T__> in__(params_r__,params_i__);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  alpha0;
            (void) alpha0;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha0 = in__.vector_lb_constrain(0,K,lp__);
            else
                alpha0 = in__.vector_lb_constrain(0,K);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  alphaD;
            (void) alphaD;  // dummy to suppress unused var warning
            if (jacobian__)
                alphaD = in__.vector_lb_constrain(0,K,lp__);
            else
                alphaD = in__.vector_lb_constrain(0,K);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  alpha2;
            (void) alpha2;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha2 = in__.vector_lub_constrain(0,2,K,lp__);
            else
                alpha2 = in__.vector_lub_constrain(0,2,K);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.positive_ordered_constrain(K,lp__);
            else
                phi = in__.positive_ordered_constrain(K);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  nugget;
            (void) nugget;  // dummy to suppress unused var warning
            if (jacobian__)
                nugget = in__.vector_lb_constrain(0,N,lp__);
            else
                nugget = in__.vector_lb_constrain(0,N);

            vector<Eigen::Matrix<T__,Eigen::Dynamic,1> > w;
            size_t dim_w_0__ = N;
            w.reserve(dim_w_0__);
            for (size_t k_0__ = 0; k_0__ < dim_w_0__; ++k_0__) {
                if (jacobian__)
                    w.push_back(in__.simplex_constrain(K,lp__));
                else
                    w.push_back(in__.simplex_constrain(K));
            }

            T__ gamma;
            (void) gamma;  // dummy to suppress unused var warning
            if (jacobian__)
                gamma = in__.scalar_lb_constrain(0,lp__);
            else
                gamma = in__.scalar_lb_constrain(0);


            // transformed parameters
            current_statement_begin__ = 55;
            validate_non_negative_index("parCov", "N", N);
            validate_non_negative_index("parCov", "N", N);
            Eigen::Matrix<T__,Eigen::Dynamic,Eigen::Dynamic>  parCov(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
            (void) parCov;  // dummy to suppress unused var warning

            stan::math::initialize(parCov, DUMMY_VAR__);
            stan::math::fill(parCov,DUMMY_VAR__);
            current_statement_begin__ = 56;
            validate_non_negative_index("w_mat", "N", N);
            validate_non_negative_index("w_mat", "K", K);
            Eigen::Matrix<T__,Eigen::Dynamic,Eigen::Dynamic>  w_mat(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(K));
            (void) w_mat;  // dummy to suppress unused var warning

            stan::math::initialize(w_mat, DUMMY_VAR__);
            stan::math::fill(w_mat,DUMMY_VAR__);


            current_statement_begin__ = 57;
            stan::math::assign(w_mat, make_w_matrix(N,K,w, pstream__));
            current_statement_begin__ = 58;
            stan::math::assign(parCov, admixed_covariance(N,K,alpha0,alphaD,alpha2,geoDist,w_mat,nugget,phi,gamma, pstream__));

            // validate transformed parameters
            for (int i0__ = 0; i0__ < N; ++i0__) {
                for (int i1__ = 0; i1__ < N; ++i1__) {
                    if (stan::math::is_uninitialized(parCov(i0__,i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: parCov" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }
            for (int i0__ = 0; i0__ < N; ++i0__) {
                for (int i1__ = 0; i1__ < K; ++i1__) {
                    if (stan::math::is_uninitialized(w_mat(i0__,i1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: w_mat" << '[' << i0__ << ']' << '[' << i1__ << ']';
                        throw std::runtime_error(msg__.str());
                    }
                }
            }

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 55;
            current_statement_begin__ = 56;

            // model body

            current_statement_begin__ = 61;
            lp_accum__.add(normal_log<propto__>(alpha0, 0, 1));
            current_statement_begin__ = 62;
            lp_accum__.add(normal_log<propto__>(alphaD, 0, 1));
            current_statement_begin__ = 63;
            lp_accum__.add(uniform_log<propto__>(alpha2, 0, 2));
            current_statement_begin__ = 64;
            lp_accum__.add(normal_log<propto__>(nugget, 0, 1));
            current_statement_begin__ = 65;
            lp_accum__.add(normal_log<propto__>(phi, 0, 1));
            current_statement_begin__ = 66;
            lp_accum__.add(normal_log<propto__>(gamma, varMeanFreqs, 0.5));
            current_statement_begin__ = 67;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 67;
                lp_accum__.add(dirichlet_log<propto__>(get_base1(w,i,"w",1), dirConPar));
            }
            current_statement_begin__ = 68;
            lp_accum__.add(wishart_log<propto__>(LobsCov, L, parCov));

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("alpha0");
        names__.push_back("alphaD");
        names__.push_back("alpha2");
        names__.push_back("phi");
        names__.push_back("nugget");
        names__.push_back("w");
        names__.push_back("gamma");
        names__.push_back("parCov");
        names__.push_back("w_mat");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back(K);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_space_multiK_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d alpha0 = in__.vector_lb_constrain(0,K);
        vector_d alphaD = in__.vector_lb_constrain(0,K);
        vector_d alpha2 = in__.vector_lub_constrain(0,2,K);
        vector_d phi = in__.positive_ordered_constrain(K);
        vector_d nugget = in__.vector_lb_constrain(0,N);
        vector<vector_d> w;
        size_t dim_w_0__ = N;
        for (size_t k_0__ = 0; k_0__ < dim_w_0__; ++k_0__) {
            w.push_back(in__.simplex_constrain(K));
        }
        double gamma = in__.scalar_lb_constrain(0);
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(alpha0[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(alphaD[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(alpha2[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(phi[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(nugget[k_0__]);
            }
            for (int k_1__ = 0; k_1__ < K; ++k_1__) {
                for (int k_0__ = 0; k_0__ < N; ++k_0__) {
                vars__.push_back(w[k_0__][k_1__]);
                }
            }
        vars__.push_back(gamma);

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            current_statement_begin__ = 55;
            validate_non_negative_index("parCov", "N", N);
            validate_non_negative_index("parCov", "N", N);
            matrix_d parCov(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(N));
            (void) parCov;  // dummy to suppress unused var warning

            stan::math::initialize(parCov, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(parCov,DUMMY_VAR__);
            current_statement_begin__ = 56;
            validate_non_negative_index("w_mat", "N", N);
            validate_non_negative_index("w_mat", "K", K);
            matrix_d w_mat(static_cast<Eigen::VectorXd::Index>(N),static_cast<Eigen::VectorXd::Index>(K));
            (void) w_mat;  // dummy to suppress unused var warning

            stan::math::initialize(w_mat, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(w_mat,DUMMY_VAR__);


            current_statement_begin__ = 57;
            stan::math::assign(w_mat, make_w_matrix(N,K,w, pstream__));
            current_statement_begin__ = 58;
            stan::math::assign(parCov, admixed_covariance(N,K,alpha0,alphaD,alpha2,geoDist,w_mat,nugget,phi,gamma, pstream__));

            // validate transformed parameters
            current_statement_begin__ = 55;
            current_statement_begin__ = 56;

            // write transformed parameters
            for (int k_1__ = 0; k_1__ < N; ++k_1__) {
                for (int k_0__ = 0; k_0__ < N; ++k_0__) {
                vars__.push_back(parCov(k_0__, k_1__));
                }
            }
            for (int k_1__ = 0; k_1__ < K; ++k_1__) {
                for (int k_0__ = 0; k_0__ < N; ++k_0__) {
                vars__.push_back(w_mat(k_0__, k_1__));
                }
            }

            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_space_multiK";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alphaD" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha2" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nugget" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "w" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "gamma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_1__ = 1; k_1__ <= N; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "parCov" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "w_mat" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha0" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alphaD" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha2" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nugget" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_1__ = 1; k_1__ <= (K - 1); ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "w" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "gamma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_1__ = 1; k_1__ <= N; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "parCov" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "w_mat" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
    }

}; // model

}

typedef model_space_multiK_namespace::model_space_multiK stan_model;


#endif
