// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_multiK_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 59> locations_array__ =
  {" (found before start of program)",
  " (in 'multiK', line 35, column 1 to column 25)",
  " (in 'multiK', line 36, column 1 to column 21)",
  " (in 'multiK', line 37, column 3 to column 29)",
  " (in 'multiK', line 38, column 1 to column 26)",
  " (in 'multiK', line 41, column 1 to column 20)",
  " (in 'multiK', line 42, column 1 to column 19)",
  " (in 'multiK', line 43, column 1 to column 30)",
  " (in 'multiK', line 44, column 1 to column 62)",
  " (in 'multiK', line 47, column 1 to column 22)",
  " (in 'multiK', line 48, column 1 to column 19)",
  " (in 'multiK', line 49, column 1 to column 34)",
  " (in 'multiK', line 50, column 15 to column 43)",
  " (in 'multiK', line 50, column 1 to column 43)",
  " (in 'multiK', line 51, column 1 to column 29)",
  " (in 'multiK', line 22, column 1 to column 16)",
  " (in 'multiK', line 23, column 1 to column 16)",
  " (in 'multiK', line 24, column 1 to column 18)",
  " (in 'multiK', line 25, column 8 to column 9)",
  " (in 'multiK', line 25, column 10 to column 11)",
  " (in 'multiK', line 25, column 1 to column 20)",
  " (in 'multiK', line 26, column 1 to column 19)",
  " (in 'multiK', line 29, column 8 to column 9)",
  " (in 'multiK', line 29, column 10 to column 11)",
  " (in 'multiK', line 29, column 1 to column 21)",
  " (in 'multiK', line 30, column 8 to column 9)",
  " (in 'multiK', line 30, column 1 to column 21)",
  " (in 'multiK', line 31, column 1 to column 23)",
  " (in 'multiK', line 32, column 1 to column 31)",
  " (in 'multiK', line 35, column 18 to column 19)",
  " (in 'multiK', line 37, column 19 to column 20)",
  " (in 'multiK', line 38, column 7 to column 8)",
  " (in 'multiK', line 38, column 18 to column 19)",
  " (in 'multiK', line 41, column 8 to column 9)",
  " (in 'multiK', line 41, column 10 to column 11)",
  " (in 'multiK', line 42, column 8 to column 9)",
  " (in 'multiK', line 42, column 10 to column 11)",
  " (in 'multiK', line 3, column 9 to column 10)",
  " (in 'multiK', line 3, column 11 to column 12)",
  " (in 'multiK', line 3, column 2 to column 21)",
  " (in 'multiK', line 4, column 9 to column 10)",
  " (in 'multiK', line 4, column 11 to column 12)",
  " (in 'multiK', line 4, column 2 to column 22)",
  " (in 'multiK', line 5, column 2 to column 29)",
  " (in 'multiK', line 6, column 2 to column 32)",
  " (in 'multiK', line 8, column 3 to column 55)",
  " (in 'multiK', line 7, column 15 to line 9, column 3)",
  " (in 'multiK', line 7, column 2 to line 9, column 3)",
  " (in 'multiK', line 10, column 2 to column 28)",
  " (in 'multiK', line 11, column 2 to column 16)",
  " (in 'multiK', line 2, column 94 to line 12, column 2)",
  " (in 'multiK', line 14, column 9 to column 10)",
  " (in 'multiK', line 14, column 11 to column 12)",
  " (in 'multiK', line 14, column 2 to column 20)",
  " (in 'multiK', line 16, column 3 to column 34)",
  " (in 'multiK', line 15, column 15 to line 17, column 3)",
  " (in 'multiK', line 15, column 2 to line 17, column 3)",
  " (in 'multiK', line 18, column 2 to column 15)",
  " (in 'multiK', line 13, column 53 to line 19, column 2)"};
template <typename T2__, typename T3__, typename T4__, typename T5__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_stan_scalar<T5__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, stan::base_type_t<T4__>, T5__>,-1,-1>
admixed_covariance(const int& N, const int& K, const T2__& w_mat_arg__,
                   const T3__& nugget_arg__, const T4__& phi_arg__,
                   const T5__& gamma, std::ostream* pstream__);
template <typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T2__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<T2__>,-1,-1>
make_w_matrix(const int& N, const int& K,
              const std::vector<Eigen::Matrix<T2__,-1,1>>& w, std::ostream*
              pstream__);
template <typename T2__, typename T3__, typename T4__, typename T5__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_stan_scalar<T5__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T2__>,
                stan::base_type_t<T3__>, stan::base_type_t<T4__>, T5__>,-1,-1>
admixed_covariance(const int& N, const int& K, const T2__& w_mat_arg__,
                   const T3__& nugget_arg__, const T4__& phi_arg__,
                   const T5__& gamma, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>, T5__>;
  int current_statement__ = 0;
  const auto& w_mat = stan::math::to_ref(w_mat_arg__);
  const auto& nugget = stan::math::to_ref(nugget_arg__);
  const auto& phi = stan::math::to_ref(phi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 37;
    stan::math::validate_non_negative_index("parCov", "N", N);
    current_statement__ = 38;
    stan::math::validate_non_negative_index("parCov", "N", N);
    Eigen::Matrix<local_scalar_t__,-1,-1> parCov =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
    current_statement__ = 40;
    stan::math::validate_non_negative_index("Nug_mat", "N", N);
    current_statement__ = 41;
    stan::math::validate_non_negative_index("Nug_mat", "N", N);
    Eigen::Matrix<local_scalar_t__,-1,-1> Nug_mat =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
    current_statement__ = 43;
    stan::model::assign(parCov, stan::math::rep_matrix(0, N, N),
      "assigning variable parCov");
    current_statement__ = 44;
    stan::model::assign(Nug_mat, stan::math::diag_matrix(nugget),
      "assigning variable Nug_mat");
    current_statement__ = 47;
    for (int k = 1; k <= K; ++k) {
      current_statement__ = 45;
      stan::model::assign(parCov,
        stan::math::add(stan::model::deep_copy(parCov),
          stan::math::multiply(
            stan::math::tcrossprod(
              stan::math::to_matrix(
                stan::model::rvalue(w_mat, "w_mat",
                  stan::model::index_omni(), stan::model::index_uni(k)))),
            stan::model::rvalue(phi, "phi", stan::model::index_uni(k)))),
        "assigning variable parCov");
    }
    current_statement__ = 48;
    stan::model::assign(parCov,
      stan::math::add(stan::model::deep_copy(parCov),
        stan::math::add(gamma, Nug_mat)), "assigning variable parCov");
    current_statement__ = 49;
    return parCov;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T2__, stan::require_all_t<stan::is_stan_scalar<T2__>>*>
Eigen::Matrix<stan::promote_args_t<T2__>,-1,-1>
make_w_matrix(const int& N, const int& K,
              const std::vector<Eigen::Matrix<T2__,-1,1>>& w, std::ostream*
              pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T2__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 51;
    stan::math::validate_non_negative_index("w_mat", "N", N);
    current_statement__ = 52;
    stan::math::validate_non_negative_index("w_mat", "K", K);
    Eigen::Matrix<local_scalar_t__,-1,-1> w_mat =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
    current_statement__ = 56;
    for (int i = 1; i <= N; ++i) {
      current_statement__ = 54;
      stan::model::assign(w_mat,
        stan::math::to_row_vector(
          stan::model::rvalue(w, "w", stan::model::index_uni(i))),
        "assigning variable w_mat", stan::model::index_uni(i));
    }
    current_statement__ = 57;
    return w_mat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_multiK final : public model_base_crtp<model_multiK> {
private:
  int K;
  int N;
  int L;
  Eigen::Matrix<double,-1,-1> obsCov_data__;
  double varMeanFreqs;
  Eigen::Matrix<double,-1,-1> LobsCov_data__;
  Eigen::Matrix<double,-1,1> dirConPar_data__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> obsCov{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> LobsCov{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> dirConPar{nullptr, 0};
public:
  ~model_multiK() {}
  model_multiK(stan::io::var_context& context__, unsigned int
               random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_multiK_namespace::model_multiK";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 15;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 15;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "N", N, 2);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "L", "int",
        std::vector<size_t>{});
      L = std::numeric_limits<int>::min();
      current_statement__ = 17;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "L", L, (N + 1));
      current_statement__ = 18;
      stan::math::validate_non_negative_index("obsCov", "N", N);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("obsCov", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "obsCov", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(N)});
      obsCov_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                        std::numeric_limits<double>::quiet_NaN());
      new (&obsCov)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(obsCov_data__.data(), N, N);
      {
        std::vector<local_scalar_t__> obsCov_flat__;
        current_statement__ = 20;
        obsCov_flat__ = context__.vals_r("obsCov");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 20;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 20;
            stan::model::assign(obsCov, obsCov_flat__[(pos__ - 1)],
              "assigning variable obsCov", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 20;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 21;
      context__.validate_dims("data initialization", "varMeanFreqs",
        "double", std::vector<size_t>{});
      varMeanFreqs = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 21;
      varMeanFreqs = context__.vals_r("varMeanFreqs")[(1 - 1)];
      current_statement__ = 22;
      stan::math::validate_non_negative_index("LobsCov", "N", N);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("LobsCov", "N", N);
      current_statement__ = 24;
      LobsCov_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, N,
                         std::numeric_limits<double>::quiet_NaN());
      new (&LobsCov)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(LobsCov_data__.data(), N, N);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("dirConPar", "K", K);
      current_statement__ = 26;
      dirConPar_data__ = Eigen::Matrix<double,-1,1>::Constant(K,
                           std::numeric_limits<double>::quiet_NaN());
      new (&dirConPar)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(dirConPar_data__.data(), K);
      current_statement__ = 27;
      stan::model::assign(LobsCov, stan::math::multiply(L, obsCov),
        "assigning variable LobsCov");
      current_statement__ = 28;
      stan::model::assign(dirConPar, stan::math::rep_vector(0.1, K),
        "assigning variable dirConPar");
      current_statement__ = 29;
      stan::math::validate_non_negative_index("phi", "K", K);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("nugget", "N", N);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("w", "N", N);
      current_statement__ = 32;
      stan::math::validate_positive_index("w", "K", K);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("parCov", "N", N);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("parCov", "N", N);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("w_mat", "N", N);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("w_mat", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = K + 1 + N + (N * (K - 1));
  }
  inline std::string model_name() const final {
    return "model_multiK";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_multiK_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> phi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      phi = in__.template read_constrain_positive_ordered<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 2;
      gamma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> nugget =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 3;
      nugget = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 N);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> w =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__));
      current_statement__ = 4;
      w = in__.template read_constrain_simplex<
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
            jacobian__>(lp__, N, K);
      Eigen::Matrix<local_scalar_t__,-1,-1> parCov =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> w_mat =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, K, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(w_mat, make_w_matrix(N, K, w, pstream__),
        "assigning variable w_mat");
      current_statement__ = 8;
      stan::model::assign(parCov,
        admixed_covariance(N, K, w_mat, nugget, phi, gamma, pstream__),
        "assigning variable parCov");
      {
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(nugget, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(phi, 0, 1));
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(gamma, varMeanFreqs,
                         0.5));
        current_statement__ = 13;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 12;
          lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                           stan::model::rvalue(w, "w",
                             stan::model::index_uni(i)), dirConPar));
        }
        current_statement__ = 14;
        lp_accum__.add(stan::math::wishart_lpdf<propto__>(LobsCov, L, parCov));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_multiK_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> phi =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      phi = in__.template read_constrain_positive_ordered<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      double gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      gamma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> nugget =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      nugget = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 N);
      std::vector<Eigen::Matrix<double,-1,1>> w =
        std::vector<Eigen::Matrix<double,-1,1>>(N,
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 4;
      w = in__.template read_constrain_simplex<
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
            jacobian__>(lp__, N, K);
      Eigen::Matrix<double,-1,-1> parCov =
        Eigen::Matrix<double,-1,-1>::Constant(N, N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> w_mat =
        Eigen::Matrix<double,-1,-1>::Constant(N, K,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(phi);
      out__.write(gamma);
      out__.write(nugget);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          out__.write(w[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 7;
      stan::model::assign(w_mat, make_w_matrix(N, K, w, pstream__),
        "assigning variable w_mat");
      current_statement__ = 8;
      stan::model::assign(parCov,
        admixed_covariance(N, K, w_mat, nugget, phi, gamma, pstream__),
        "assigning variable parCov");
      if (emit_transformed_parameters__) {
        out__.write(parCov);
        out__.write(w_mat);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> phi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(phi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable phi");
      out__.write_free_positive_ordered(phi);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 2;
      gamma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, gamma);
      Eigen::Matrix<local_scalar_t__,-1,1> nugget =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(nugget,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable nugget");
      out__.write_free_lb(0, nugget);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> w =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__));
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 4;
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          current_statement__ = 4;
          stan::model::assign(w, in__.read<local_scalar_t__>(),
            "assigning variable w", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_simplex(w);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "phi", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "gamma", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "nugget", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> phi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> phi_flat__;
        current_statement__ = 1;
        phi_flat__ = context__.vals_r("phi");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(phi, phi_flat__[(pos__ - 1)],
            "assigning variable phi", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_positive_ordered(phi);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 2;
      gamma = context__.vals_r("gamma")[(1 - 1)];
      out__.write_free_lb(0, gamma);
      Eigen::Matrix<local_scalar_t__,-1,1> nugget =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> nugget_flat__;
        current_statement__ = 3;
        nugget_flat__ = context__.vals_r("nugget");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(nugget, nugget_flat__[(pos__ - 1)],
            "assigning variable nugget", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, nugget);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> w =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 4;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 4;
            stan::model::assign(w, w_flat__[(pos__ - 1)],
              "assigning variable w", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_simplex(w);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"phi", "gamma", "nugget", "w"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"parCov", "w_mat"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(N)},
                std::vector<size_t>{static_cast<size_t>(N),
                  static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "phi" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "gamma");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "nugget" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "w" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "parCov" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "w_mat" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "phi" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "gamma");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "nugget" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        param_names__.emplace_back(std::string() + "w" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "parCov" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "w_mat" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"phi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nugget\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"parameters\"},{\"name\":\"parCov\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"w_mat\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"phi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nugget\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((K -1)) + "}},\"block\":\"parameters\"},{\"name\":\"parCov\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"w_mat\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(N) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + 1) + N) + (N * K));
    const size_t num_transformed = emit_transformed_parameters * (((N * N) +
      (N * K)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((K + 1) + N) + (N * K));
    const size_t num_transformed = emit_transformed_parameters * (((N * N) +
      (N * K)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_multiK_namespace::model_multiK;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_multiK_namespace::profiles__;
}
#endif
#endif
