	rm(list=ls()) ; gc()
source("sim_figs.R")
	rm(list=ls()) ; gc()
source("populus_figs.R")
	rm(list=ls()) ; gc()
source("admixture_figs.R")
	rm(list=ls()) ; gc()
source("bear_figs.R")
	rm(list=ls()) ; gc()
