#' Example dataset used in a \code{conStruct} analysis
#' 
#' A simulated dataset containing the allele frequency 
#' and sampling coordinate data necessary to run a 
#' \code{conStruct} analysis.
#' 
#' @format A list with two elements:
#' \describe{
#'		\item{allele.frequencies}{a matrix with one row for each of 
#'			the 36 samples and one column for each of 10,000 loci, 
#'			giving the frequency of the counted allele at each locus 
#'			in each sample}
#'		\item{coords}{a matrix with one row for each of the 36 samples, 
#'			in the same order as that of the allele frequency matrix, 
#'			and two columns, the first giving the x-coordinate 
#'			(or longitude), the second giving the y-coordinate (or latitude)}
#' }
#
"conStruct.data"

#' Example \code{data.block} generated by a \code{conStruct} analysis
#' 
#' An example \code{data.block} object generated in a \code{conStruct} 
#' analysis from the raw data supplied by the user. This object is 
#' automatically saved and is used in several subsequent plotting functions.
#' 
#' @format A list with 7 elements:
#' \describe{
#'		\item{\code{N}}{the number of samples included in the analysis}
#'		\item{\code{K}}{the number of clusters/layers included in the model}
#'		\item{\code{spatial}}{a boolean indicating whether the spatial
#'			model has been specified}
#'		\item{\code{L}}{the number of loci included in the analysis}
#'		\item{\code{coords}}{a matrix with one row for each of the \code{N} samples, 
#'			in the same order as that of the \code{obsCov} matrix, 
#'			and two columns, the first giving the x-coordinate 
#'			(or longitude), the second giving the y-coordinate (or latitude)}
#'		\item{\code{obsCov}}{the sample allelic covariance matrix, 
#'			in the same order as that of the \code{coords} matrix, 
#'			with \code{N} rows and columns}
#'		\item{\code{geoDist}}{a matrix of pairwise geographic distance between , 
#'			samples in the same order as that of the \code{obsCov}, 
#'			with \code{N} rows and columns, normalized by the standard 
#'			deviation of the raw geographic distance matrix specified 
#'			by the user}
#'		\item{\code{varMeanFreqs}}{the variance of the mean allele frequencies, 
#'			averaged over choice of counted allele (passed to the model 
#'			as a prior on the global covaraince parameter)}
#' }
#
"data.block"

#' Example model output from a \code{conStruct} analysis
#' 
#' An example \code{conStruct.results} object generated by 
#' a \code{conStruct} analysis.
#' 
#' @format a list with one entry for each chain run 
#'		(specified with \code{n.chains}). The entry for each chain is named 
#'		"chain_X" for the Xth chain.  The components of the entries for each 
#'		are detailed below: 
#'		\itemize{
#'			\item \code{posterior} gives parameter estimates over the posterior 
#'					distribution of the MCMC
#'				\itemize{
#'					\item \code{n.iter} number of MCMC iterations retained for 
#'							analysis (half of the \code{n.iter} argument 
#'							specified in the function call)
#'					\item \code{lpd} vector of log posterior density over the retained 
#'							MCMC iterations.
#'					\item \code{nuggets} matrix of estimated nugget parameters with 
#'							one row per MCMC iteration and one column per sample.
#'					\item \code{par.cov} array of estimated parametric covariance matrices, 
#'							for which the first dimension is the number of MCMC iterations.
#'					\item \code{gamma} vector of estimated gamma parameter.
#'					\item \code{layer.params} list summarizing estimates of layer-specific 
#'							parameters. There is one entry for each layer specified, and the 
#'							entry for the kth layer is named "Layer_k".
#'						\itemize{
#'							\item \code{alpha0} vector of estimated alpha0 parameter in the 
#'									kth layer.
#'							\item \code{alphaD} vector of estimated alphaD parameter in the 
#'									kth layer.
#'							\item \code{alpha2} vector of estimated alpha2 parameter in the 
#'									kth layer.
#'							\item \code{mu} vector of estimated mu parameter in the 
#'									kth layer.
#'							\item \code{layer.cov} vector of estimated layer-specific 
#'									covariance parameter in the kth layer.
#'						}
#'					\item \code{admix.proportions} array of estimated admixture proportions.
#'							The first dimension is the number of MCMC iterations, 
#'							the second is the number of samples, 
#'								and the third is the number of layers.
#'				}
#'		\item \code{MAP} gives point estimates of the parameters listed in the \code{posterior}
#'							list described above. Values are indexed at the MCMC iteration 
#'							with the greatest posterior probability.
#'				\itemize{
#'					\item \code{index.iter} the iteration of the MCMC with the highest 
#'							posterior probability, which is used to index all parameters 
#'							included in the \code{MAP} list
#'					\item \code{lpd} the greatest value of the posterior probability
#'					\item \code{nuggets} point estimate of nugget parameters
#'					\item \code{par.cov} point estimate of parametric covariance
#'					\item \code{gamma} point estimate of gamma parameter
#'					\item \code{layer.params} point estimates of all layer-specific parameters 
#'					\item \code{admix.proportions} point estimates of admixture proportions.
#'				}
#'		}
#
"conStruct.results"